language: go

sudo: false

os:
  - linux
  - osx

env:
  - GO15VENDOREXPERIMENT=1

go:
  - 1.5
  - tip

services:
  - elasticsearch

install:
 - go get -u github.com/golang/lint/golint
 - go get -u golang.org/x/tools/cmd/goimports

before_script:
  - sleep 10

script:
 - go vet ./cmd/...
 - go vet ./traffic/...
 - diff <(goimports -d ./traffic/...) <(printf "")
 - diff <(golint ./traffic/...) <(printf "")
 - diff <(golint ./cmd/...) <(printf "")
 - go test -v -cpu=2 ./traffic/...
 - go test -v -cpu=2 ./cmd/...
 - go test -v -cpu=1,2,4 -short -race ./traffic/...
 - go test -v -cpu=1,2,4 -short -race ./cmd/...

